package com.podolsk.resourcecollector;
import android.app.*;import android.os.*;import android.content.pm.PackageManager;import android.widget.*;import java.io.*;import rikka.shizuku.Shizuku;
public class MainActivity extends Activity{
 TextView status;Button copy;static final int REQ=1001;final String SRC="/sdcard/Android/data/com.launcher.brgame/files",DST="/sdcard/Download/PodolskResources";
 private final Shizuku.OnRequestPermissionResultListener listener=(r,g)->{if(r==REQ)refresh();};
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(40,60,40,40);TextView h=new TextView(this);h.setText("Podolsk Resource Collector 2.0");h.setTextSize(25);l.addView(h);TextView i=new TextView(this);i.setText("Для Android 13 через Shizuku.\n\n1. Установи и запусти Shizuku.\n2. Нажми «Дать доступ Shizuku».\n3. Нажми «Скопировать ресурсы».\n\nИсточник: "+SRC+"\nКопия: "+DST);i.setTextSize(16);i.setPadding(0,24,0,24);l.addView(i);Button a=new Button(this);a.setText("1. Дать доступ Shizuku");a.setOnClickListener(v->request());l.addView(a);copy=new Button(this);copy.setText("2. Скопировать ресурсы");copy.setOnClickListener(v->new Thread(this::copyFiles).start());l.addView(copy);status=new TextView(this);status.setPadding(0,24,0,0);l.addView(status);setContentView(l);Shizuku.addRequestPermissionResultListener(listener);refresh();}
 void refresh(){try{if(!Shizuku.pingBinder()){status.setText("Shizuku не запущен.");copy.setEnabled(false);return;}boolean ok=Shizuku.checkSelfPermission()==PackageManager.PERMISSION_GRANTED;status.setText(ok?"Shizuku: доступ разрешён.":"Shizuku запущен, нужен доступ.");copy.setEnabled(ok);}catch(Exception e){status.setText("Shizuku недоступен.");copy.setEnabled(false);}}
 void request(){try{if(!Shizuku.pingBinder()){status.setText("Сначала запусти Shizuku.");return;}Shizuku.requestPermission(REQ);}catch(Exception e){status.setText("Ошибка: "+e.getMessage());}}
 void copyFiles(){runOnUiThread(()->{copy.setEnabled(false);status.setText("Копирование…");});try{String cmd="mkdir -p '"+DST+"' && for n in audio jsons mesh resources textures; do [ ! -e '"+SRC+"/'$n ] || cp -R '"+SRC+"/'$n '"+DST+"/'; done; find '"+SRC+"' -maxdepth 1 -type f -name '*.bpc' -exec cp -f {} '"+DST+"/' \\;";Process p=Shizuku.newProcess(new String[]{"sh","-c",cmd},null,null);StringBuilder e=new StringBuilder();BufferedReader br=new BufferedReader(new InputStreamReader(p.getErrorStream()));String s;while((s=br.readLine())!=null)e.append(s).append("\n");int c=p.waitFor();runOnUiThread(()->status.setText(c==0?"Готово! Папка: Download/PodolskResources":"Ошибка:\n"+e));}catch(Exception e){runOnUiThread(()->status.setText("Ошибка: "+e.getMessage()));}finally{runOnUiThread(()->copy.setEnabled(true));}}
 protected void onDestroy(){Shizuku.removeRequestPermissionResultListener(listener);super.onDestroy();}
}